import type { IndustryProfile } from "./types";

export const industries: readonly IndustryProfile[] = [
  {
    id: "software",
    label: "Software / Platform",
    field: "software engineering",
    titleTracks: {
      early: ["Software Engineer", "Frontend Engineer", "Backend Engineer"],
      established: ["Senior Software Engineer", "Platform Engineer", "Product Engineer"],
      senior: ["Staff Software Engineer", "Principal Engineer", "Engineering Manager"],
    },
    employers: ["Stripe", "Datadog", "Shopify", "Linear", "Atlassian", "Vercel"],
    degreeFields: ["Computer Science", "Electrical Engineering", "Human-Computer Interaction"],
    competencies: ["distributed systems", "developer experience", "product infrastructure", "observability", "accessibility"],
    tools: ["TypeScript", "React", "Node.js", "PostgreSQL", "Kubernetes", "AWS", "GraphQL"],
    metrics: ["p95 latency", "deployment frequency", "incident volume", "activation rate", "test coverage"],
    bodies: ["AWS Certified Solutions Architect", "Certified Kubernetes Application Developer"],
  },
  {
    id: "product-design",
    label: "Product Design",
    field: "digital product design",
    titleTracks: {
      early: ["Product Designer", "UX Designer", "Interaction Designer"],
      established: ["Senior Product Designer", "Design Systems Designer", "UX Research Lead"],
      senior: ["Principal Product Designer", "Design Lead", "Head of Product Design"],
    },
    employers: ["Figma", "Notion", "Airbnb", "Intercom", "Spotify", "Dropbox"],
    degreeFields: ["Interaction Design", "Graphic Design", "Human-Computer Interaction"],
    competencies: ["interaction design", "research synthesis", "design systems", "service mapping", "accessibility"],
    tools: ["Figma", "FigJam", "ProtoPie", "Maze", "Design tokens", "WCAG"],
    metrics: ["task completion", "time-to-value", "support tickets", "prototype confidence", "component adoption"],
    bodies: ["NN/g UX Certification", "IAAP CPACC", "Design Leadership Forum"],
  },
  {
    id: "finance",
    label: "Finance / Strategy",
    field: "financial planning and capital strategy",
    titleTracks: {
      early: ["Financial Analyst", "Investment Analyst", "FP&A Analyst"],
      established: ["Finance Manager", "Portfolio Analyst", "Strategic Finance Lead"],
      senior: ["Director of Finance", "VP Finance", "Head of Corporate Strategy"],
    },
    employers: ["BlackRock", "Goldman Sachs", "Revolut", "Block", "Aon", "Capital One"],
    degreeFields: ["Finance", "Economics", "Applied Mathematics"],
    competencies: ["valuation", "forecasting", "portfolio risk", "capital allocation", "board reporting"],
    tools: ["Excel", "SQL", "Python", "Bloomberg Terminal", "Tableau", "Anaplan"],
    metrics: ["forecast variance", "gross margin", "working capital", "portfolio exposure", "monthly close"],
    bodies: ["CFA Level II", "FRM", "CPA"],
  },
  {
    id: "healthcare",
    label: "Healthcare Operations",
    field: "clinical operations",
    titleTracks: {
      early: ["Clinical Operations Coordinator", "Research Associate", "Care Operations Analyst"],
      established: ["Clinical Program Manager", "Quality Improvement Lead", "Healthcare Consultant"],
      senior: ["Director of Clinical Operations", "Head of Population Health", "Practice Administrator"],
    },
    employers: ["Mayo Clinic", "Cleveland Clinic", "Kaiser Permanente", "Teladoc", "Cityblock Health", "Roche"],
    degreeFields: ["Public Health", "Health Systems", "Biomedical Sciences"],
    competencies: ["patient access", "quality improvement", "trial operations", "care coordination", "regulatory readiness"],
    tools: ["Epic", "REDCap", "Tableau", "HIPAA controls", "GCP", "clinical pathways"],
    metrics: ["no-show rate", "cycle time", "protocol adherence", "patient satisfaction", "readmission risk"],
    bodies: ["CPHQ", "Good Clinical Practice", "Lean Six Sigma Green Belt"],
  },
  {
    id: "academia",
    label: "Academic Research",
    field: "university research",
    titleTracks: {
      early: ["Graduate Researcher", "Research Assistant", "Teaching Fellow"],
      established: ["Postdoctoral Researcher", "Research Scientist", "Lecturer"],
      senior: ["Assistant Professor", "Principal Investigator", "Associate Professor"],
    },
    employers: ["University of Toronto", "KAIST", "MIT Media Lab", "UCL", "ETH Zurich", "Aalto University"],
    degreeFields: ["Information Experience Design", "Computer Science", "Media Arts and Sciences"],
    competencies: ["study design", "peer-reviewed writing", "grant development", "teaching", "mixed-methods research"],
    tools: ["R", "Python", "qualitative coding", "IRB protocols", "LaTeX", "field studies"],
    metrics: ["citation impact", "grant value", "sample size", "teaching evaluations", "acceptance rate"],
    bodies: ["PhD", "IRB training", "ACM reviewer"],
  },
  {
    id: "legal-policy",
    label: "Legal / Policy",
    field: "regulatory policy",
    titleTracks: {
      early: ["Policy Analyst", "Compliance Associate", "Legal Fellow"],
      established: ["Policy Manager", "Regulatory Counsel", "Compliance Lead"],
      senior: ["Director of Policy", "General Counsel", "Chief Compliance Officer"],
    },
    employers: ["OECD", "Mozilla Foundation", "DLA Piper", "World Bank", "ACLU", "Stripe"],
    degreeFields: ["Law", "Public Policy", "International Relations"],
    competencies: ["statutory analysis", "stakeholder consultation", "risk governance", "contract review", "public affairs"],
    tools: ["policy briefs", "risk registers", "legislative tracking", "LexisNexis", "data protection assessments"],
    metrics: ["review cycle time", "compliance exposure", "case volume", "policy adoption", "contract turnaround"],
    bodies: ["JD", "CIPP/E", "Bar Admission"],
  },
  {
    id: "architecture",
    label: "Architecture",
    field: "architecture and urban design",
    titleTracks: {
      early: ["Architectural Designer", "Junior Designer", "BIM Coordinator"],
      established: ["Project Architect", "Urban Designer", "Design Technology Lead"],
      senior: ["Design Director", "Principal Architect", "Studio Lead"],
    },
    employers: ["BIG", "OMA", "SOM", "Foster + Partners", "Gensler", "Heatherwick Studio"],
    degreeFields: ["Architecture", "Urban Design", "Environmental Design"],
    competencies: ["concept design", "technical coordination", "planning approvals", "material research", "client presentations"],
    tools: ["Revit", "Rhino", "Grasshopper", "AutoCAD", "Enscape", "physical models"],
    metrics: ["gross floor area", "clash count", "energy use intensity", "planning milestones", "construction packages"],
    bodies: ["Registered Architect", "LEED AP", "Passive House Designer"],
  },
  {
    id: "communications",
    label: "Communications",
    field: "brand and communications",
    titleTracks: {
      early: ["Communications Associate", "Content Strategist", "Editorial Producer"],
      established: ["Communications Manager", "Brand Editor", "Audience Development Lead"],
      senior: ["Head of Communications", "Editorial Director", "VP Brand"],
    },
    employers: ["The Atlantic", "IDEO", "Patagonia", "TED", "Monocle", "Wieden+Kennedy"],
    degreeFields: ["Journalism", "Communications", "English"],
    competencies: ["narrative strategy", "media relations", "editorial planning", "crisis communications", "audience growth"],
    tools: ["CMS", "Google Analytics", "Meltwater", "press kits", "editorial calendars"],
    metrics: ["earned media reach", "subscriber growth", "open rate", "share of voice", "engagement quality"],
    bodies: ["AP Style", "Crisis Communications Certificate", "Google Analytics Certification"],
  },
  {
    id: "operations",
    label: "Operations",
    field: "supply chain and operations",
    titleTracks: {
      early: ["Operations Analyst", "Logistics Coordinator", "Supply Planner"],
      established: ["Operations Manager", "Supply Chain Lead", "Process Improvement Manager"],
      senior: ["Director of Operations", "VP Supply Chain", "General Manager"],
    },
    employers: ["Maersk", "Unilever", "Amazon", "Flexport", "IKEA", "Toyota"],
    degreeFields: ["Industrial Engineering", "Operations Management", "Supply Chain"],
    competencies: ["capacity planning", "process design", "vendor management", "cost control", "SOP development"],
    tools: ["SAP", "Oracle ERP", "Looker", "forecasting models", "vendor scorecards"],
    metrics: ["fill rate", "cycle time", "freight variance", "inventory turns", "on-time delivery"],
    bodies: ["APICS CPIM", "PMP", "Lean Six Sigma Black Belt"],
  },
  {
    id: "education",
    label: "Education",
    field: "learning design",
    titleTracks: {
      early: ["Teacher", "Learning Designer", "Program Coordinator"],
      established: ["Curriculum Lead", "Instructional Coach", "Education Program Manager"],
      senior: ["Director of Learning", "Principal", "Head of Curriculum"],
    },
    employers: ["Khan Academy", "Teach For All", "Coursera", "Minerva Project", "General Assembly", "Pearson"],
    degreeFields: ["Education", "Learning Sciences", "Instructional Design"],
    competencies: ["curriculum design", "student support", "teacher coaching", "assessment design", "program evaluation"],
    tools: ["Canvas", "Moodle", "assessment rubrics", "learning analytics", "facilitation"],
    metrics: ["learner persistence", "assessment reliability", "course completion", "attendance", "teacher adoption"],
    bodies: ["Teaching License", "TESOL", "Instructional Design Certificate"],
  },
] as const;

export const firstNames = [
  "Mina",
  "Daniel",
  "Rina",
  "Alex",
  "Sofia",
  "Marcus",
  "Nadia",
  "Theo",
  "Iris",
  "Julian",
  "Leah",
  "Victor",
  "Yuna",
  "Amara",
] as const;

export const lastNames = [
  "Han",
  "Patel",
  "Rivera",
  "Morgan",
  "Kim",
  "Okafor",
  "Chen",
  "Santos",
  "Ibrahim",
  "Bennett",
  "Kwon",
  "Rossi",
  "Nakamura",
  "Garcia",
] as const;

export const cities = [
  "Seoul",
  "New York",
  "London",
  "Berlin",
  "Toronto",
  "Singapore",
  "Amsterdam",
  "Sydney",
  "San Francisco",
  "Paris",
  "Zurich",
  "Copenhagen",
] as const;

export const universities = [
  "Columbia University",
  "Seoul National University",
  "University College London",
  "University of Toronto",
  "KAIST",
  "National University of Singapore",
  "University of Melbourne",
  "New York University",
  "Delft University of Technology",
] as const;

export const languages = [
  "English",
  "Korean",
  "Spanish",
  "French",
  "German",
  "Mandarin",
  "Japanese",
  "Portuguese",
] as const;
