export type TechKeyword = Readonly<{
  abbreviation: string;
  text: string;
}>;

const twoCharacterTechKeywords: readonly TechKeyword[] = [
  { abbreviation: "AI", text: "Artificial Intelligence" },
  { abbreviation: "AR", text: "Augmented Reality" },
  { abbreviation: "AX", text: "AI Transformation" },
  { abbreviation: "BI", text: "Business Intelligence" },
  { abbreviation: "BT", text: "Biotechnology" },
  { abbreviation: "CD", text: "Continuous Delivery" },
  { abbreviation: "CI", text: "Continuous Integration" },
  { abbreviation: "CM", text: "Configuration Management" },
  { abbreviation: "CR", text: "Code Review" },
  { abbreviation: "CS", text: "Customer Success" },
  { abbreviation: "CV", text: "Computer Vision" },
  { abbreviation: "CX", text: "Customer Experience" },
  { abbreviation: "DB", text: "Database" },
  { abbreviation: "DC", text: "Data Center" },
  { abbreviation: "DL", text: "Deep Learning" },
  { abbreviation: "DM", text: "Data Mining" },
  { abbreviation: "DR", text: "Disaster Recovery" },
  { abbreviation: "DS", text: "Data Science" },
  { abbreviation: "DT", text: "Digital Twin" },
  { abbreviation: "DX", text: "Digital Transformation" },
  { abbreviation: "EC", text: "Edge Computing" },
  { abbreviation: "EM", text: "Email Marketing" },
  { abbreviation: "FE", text: "Front End" },
  { abbreviation: "FI", text: "Financial Institution" },
  { abbreviation: "FX", text: "Foreign Exchange" },
  { abbreviation: "GC", text: "Garbage Collection" },
  { abbreviation: "GD", text: "Game Development" },
  { abbreviation: "HR", text: "Human Resources" },
  { abbreviation: "IA", text: "Information Architecture" },
  { abbreviation: "IC", text: "Integrated Circuit" },
  { abbreviation: "ID", text: "Identity" },
  { abbreviation: "IM", text: "Instant Messaging" },
  { abbreviation: "IP", text: "Intellectual Property" },
  { abbreviation: "IR", text: "Information Retrieval" },
  { abbreviation: "IS", text: "Information Systems" },
  { abbreviation: "IT", text: "Information Technology" },
  { abbreviation: "KB", text: "Knowledge Base" },
  { abbreviation: "KR", text: "Knowledge Representation" },
  { abbreviation: "MA", text: "Marketing Automation" },
  { abbreviation: "MB", text: "Mobile Banking" },
  { abbreviation: "ML", text: "Machine Learning" },
  { abbreviation: "MR", text: "Mixed Reality" },
  { abbreviation: "NC", text: "Network Computing" },
  { abbreviation: "NG", text: "Next Generation" },
  { abbreviation: "NL", text: "Natural Language" },
  { abbreviation: "OA", text: "Office Automation" },
  { abbreviation: "OK", text: "Operational Knowledge" },
  { abbreviation: "OM", text: "Operations Management" },
  { abbreviation: "OO", text: "Object-Oriented" },
  { abbreviation: "OP", text: "Operations" },
  { abbreviation: "OS", text: "Operating System" },
  { abbreviation: "OT", text: "Operational Technology" },
  { abbreviation: "PC", text: "Personal Computer" },
  { abbreviation: "PE", text: "Prompt Engineering" },
  { abbreviation: "PI", text: "Product Information" },
  { abbreviation: "PL", text: "Programming Language" },
  { abbreviation: "PM", text: "Product Management" },
  { abbreviation: "PO", text: "Product Owner" },
  { abbreviation: "PR", text: "Public Relations" },
  { abbreviation: "PS", text: "Payment Services" },
  { abbreviation: "QA", text: "Quality Assurance" },
  { abbreviation: "QC", text: "Quantum Computing" },
  { abbreviation: "RD", text: "Research and Development" },
  { abbreviation: "RE", text: "Requirements Engineering" },
  { abbreviation: "RF", text: "Radio Frequency" },
  { abbreviation: "RL", text: "Reinforcement Learning" },
  { abbreviation: "RM", text: "Risk Management" },
  { abbreviation: "SA", text: "Solutions Architecture" },
  { abbreviation: "SC", text: "Supply Chain" },
  { abbreviation: "SD", text: "Software Development" },
  { abbreviation: "SE", text: "Software Engineering" },
  { abbreviation: "SI", text: "System Integration" },
  { abbreviation: "SM", text: "Social Media" },
  { abbreviation: "SO", text: "Search Optimization" },
  { abbreviation: "SP", text: "Service Provider" },
  { abbreviation: "SR", text: "System Reliability" },
  { abbreviation: "SS", text: "Security Services" },
  { abbreviation: "ST", text: "Software Testing" },
  { abbreviation: "SW", text: "Software" },
  { abbreviation: "TA", text: "Technical Architecture" },
  { abbreviation: "TC", text: "Test Case" },
  { abbreviation: "TD", text: "Technical Debt" },
  { abbreviation: "TF", text: "TensorFlow" },
  { abbreviation: "TM", text: "Technology Management" },
  { abbreviation: "TP", text: "Technology Platform" },
  { abbreviation: "TS", text: "TypeScript" },
  { abbreviation: "UI", text: "User Interface" },
  { abbreviation: "UX", text: "User Experience" },
  { abbreviation: "VC", text: "Venture Capital" },
  { abbreviation: "VM", text: "Virtual Machine" },
  { abbreviation: "VR", text: "Virtual Reality" },
  { abbreviation: "XR", text: "Extended Reality" },
] as const;

const threeCharacterTechKeywords: readonly TechKeyword[] = [
  { abbreviation: "AGI", text: "Artificial General Intelligence" },
  { abbreviation: "API", text: "Application Programming Interface" },
  { abbreviation: "CDN", text: "Content Delivery Network" },
  { abbreviation: "CLI", text: "Command Line Interface" },
  { abbreviation: "CRM", text: "Customer Relationship Management" },
  { abbreviation: "DAO", text: "Decentralized Autonomous Organization" },
  { abbreviation: "ERP", text: "Enterprise Resource Planning" },
  { abbreviation: "ESG", text: "Environmental, Social, and Governance" },
  { abbreviation: "GPT", text: "Generative Pre-trained Transformer" },
  { abbreviation: "GPU", text: "Graphics Processing Unit" },
  { abbreviation: "IDE", text: "Integrated Development Environment" },
  { abbreviation: "IoT", text: "Internet of Things" },
  { abbreviation: "KPI", text: "Key Performance Indicator" },
  { abbreviation: "LLM", text: "Large Language Model" },
  { abbreviation: "MVP", text: "Minimum Viable Product" },
  { abbreviation: "NFT", text: "Non-Fungible Token" },
  { abbreviation: "NLP", text: "Natural Language Processing" },
  { abbreviation: "NPU", text: "Neural Processing Unit" },
  { abbreviation: "RAG", text: "Retrieval-Augmented Generation" },
  { abbreviation: "RPA", text: "Robotic Process Automation" },
  { abbreviation: "SDK", text: "Software Development Kit" },
  { abbreviation: "SRE", text: "Site Reliability Engineering" },
  { abbreviation: "VLM", text: "Vision-Language Model" },
] as const;

export const techKeywords: readonly TechKeyword[] = twoCharacterTechKeywords.flatMap((keyword, index) => {
  const threeCharacterKeyword = index % 4 === 3
    ? threeCharacterTechKeywords[Math.floor(index / 4)]
    : undefined;

  return threeCharacterKeyword ? [keyword, threeCharacterKeyword] : [keyword];
});

export function techKeywordAt(index: number) {
  return techKeywords[index % techKeywords.length]!;
}
