export const lyricCues = [
  ["The", "Signal", "Keeps", "Its", "Own", "Time"],
  ["The", "Light", "Arrives", "Before", "The", "Sound"],
  ["No", "One", "Waits", "For", "The", "Last", "Train"],
  ["We", "Carry", "The", "Same", "Transmission"],
] as const;

export const lyricWordTimings = [
  { cueIndex: 0, durationMs: 250 },
  { cueIndex: 0, durationMs: 320 },
  { cueIndex: 0, durationMs: 390 },
  { cueIndex: 0, durationMs: 230 },
  { cueIndex: 0, durationMs: 310 },
  { cueIndex: 0, durationMs: 600 },
  { cueIndex: 1, durationMs: 260 },
  { cueIndex: 1, durationMs: 360 },
  { cueIndex: 1, durationMs: 560 },
  { cueIndex: 1, durationMs: 420 },
  { cueIndex: 1, durationMs: 220 },
  { cueIndex: 1, durationMs: 680 },
  { cueIndex: 2, durationMs: 280 },
  { cueIndex: 2, durationMs: 260 },
  { cueIndex: 2, durationMs: 440 },
  { cueIndex: 2, durationMs: 210 },
  { cueIndex: 2, durationMs: 190 },
  { cueIndex: 2, durationMs: 330 },
  { cueIndex: 2, durationMs: 640 },
  { cueIndex: 3, durationMs: 300 },
  { cueIndex: 3, durationMs: 400 },
  { cueIndex: 3, durationMs: 220 },
  { cueIndex: 3, durationMs: 370 },
  { cueIndex: 3, durationMs: 760 },
] as const;
