import type { InstagramStoryRow } from "./types";

export const instagramStoryRows: readonly InstagramStoryRow[] = [
  [
    { id: "seoah-k", handle: "seoah._", image: "/images/bastille-day/01.jpg" },
    { id: "min-j", handle: "__min.j", image: "/images/bastille-day/02.jpg" },
    { id: "jiwon-lee", handle: "jiwon.lee", image: "/images/bastille-day/03.jpg" },
    { id: "yoona-k", handle: "yooni__", image: "/images/bastille-day/04.jpg" },
    { id: "chae-e", handle: "chaaee", image: "/images/bastille-day/05.jpg" },
    { id: "hyun-lee", handle: "leehyun_", image: "/images/bastille-day/06.jpg" },
    { id: "minji-oh", handle: "mj._.o", image: "/images/bastille-day/07.jpg" },
    { id: "sol-e", handle: "sol._.e", image: "/images/bastille-day/08.jpg" },
  ],
  [
    { id: "yujin-k", handle: "_yujin.k", image: "/images/bastille-day/09.jpg" },
    { id: "hyejin-k", handle: "hye._.j", image: "/images/bastille-day/10.jpg" },
    { id: "jin-seo", handle: "02_jin", image: "/images/bastille-day/11.jpg" },
    { id: "arin-k", handle: "arin___", image: "/images/bastille-day/12.jpg" },
    { id: "joeun-k", handle: "jo._.eun", image: "/images/bastille-day/13.jpg" },
    { id: "bora-k", handle: "bora___", image: "/images/bastille-day/14.jpg" },
    { id: "minseok-k", handle: "min._.seok", image: "/images/bastille-day/15.jpg" },
    { id: "daon-lee", handle: "daon.lee", image: "/images/bastille-day/16.jpg" },
  ],
  [
    { id: "seorin-k", handle: "__seorin", image: "/images/bastille-day/17.jpg" },
    { id: "taeo-k", handle: "tae._.o", image: "/images/bastille-day/18.jpg" },
    { id: "sujin-cho", handle: "sujin.cho", image: "/images/bastille-day/19.jpg" },
    { id: "won-i", handle: "_woni", image: "/images/bastille-day/20.jpg" },
    { id: "danbi-k", handle: "danbi_", image: "/images/bastille-day/21.jpg" },
    { id: "junghyun-k", handle: "jung._.h", image: "/images/bastille-day/22.jpg" },
    { id: "yumi-k", handle: "yumi____", image: "/images/bastille-day/23.jpg" },
    { id: "haneul-k", handle: "ha.neul", image: "/images/bastille-day/24.jpg" },
  ],
  [
    { id: "eunchae-k", handle: "eun._.chae", image: "/images/bastille-day/25.jpg" },
    { id: "jihoon-k", handle: "jihoon___", image: "/images/bastille-day/26.jpg" },
    { id: "mijoo-k", handle: "mijoo._", image: "/images/bastille-day/27.jpg" },
    { id: "yeon-k", handle: "yeon.___", image: "/images/bastille-day/28.jpg" },
    { id: "seulgi-k", handle: "seul._.gi", image: "/images/bastille-day/29.jpg" },
    { id: "hwan-lee", handle: "hwan.lee", image: "/images/bastille-day/30.jpg" },
    { id: "aerin-k", handle: "_aerin", image: "/images/bastille-day/31.jpg" },
    { id: "seojin-k", handle: "s.__jin", image: "/images/bastille-day/32.jpg" },
  ],
  [
    { id: "rae-lee", handle: "lee._.rae", image: "/images/bastille-day/33.jpg" },
    { id: "yoona-park", handle: "yoon._.a", image: "/images/bastille-day/34.jpg" },
    { id: "chae-k", handle: "chae.__.k", image: "/images/bastille-day/35.jpg" },
    { id: "hyewon-k", handle: "hye._.won", image: "/images/bastille-day/36.jpg" },
    { id: "joomin-k", handle: "joo._.min", image: "/images/bastille-day/37.jpg" },
    { id: "hiyeon-k", handle: "hi._.yeon", image: "/images/bastille-day/38.jpg" },
    { id: "byeolee-k", handle: "byul._.e", image: "/images/bastille-day/39.jpg" },
    { id: "jiwoo-k", handle: "_ji._.woo", image: "/images/bastille-day/40.jpg" },
  ],
  [
    { id: "minah-k", handle: "min._.ah", image: "/images/bastille-day/41.jpg" },
    { id: "seungho-k", handle: "seung._.h", image: "/images/bastille-day/42.jpg" },
    { id: "dahye-k", handle: "dahye.__", image: "/images/bastille-day/43.jpg" },
    { id: "hyunseo-k", handle: "hyun._.seo", image: "/images/bastille-day/44.jpg" },
    { id: "woojin-k", handle: "w._.jin", image: "/images/bastille-day/45.jpg" },
    { id: "nari-k", handle: "nari._", image: "/images/bastille-day/46.jpg" },
    { id: "eunsol-k", handle: "eun._.sol", image: "/images/bastille-day/47.jpg" },
    { id: "kyungmin-k", handle: "kyung._.m", image: "/images/bastille-day/48.jpg" },
  ],
];
